title: Byeong Hyeon, So
logo: "https://github.com/byeonghyeonSo/byeonghyeonSo.github.io/blob/main/so_profile.jpg?raw=true"
description: >
    Data Analyst & Social Justice Enthusiast.
    <br><br>
    "All models are wrong, but some are useful." by George Box, Statistician
    <br><br>
    <a href="https://www.linkedin.com/in/byeong-hyeon-so-6849611a2/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
