title: Byeong Hyeon So
logo: "/assets/img/so1.png?raw=true"
description: >
    Data Scientist & Social Justice Enthusiast.
    <br><br>
    <a href="https://www.linkedin.com/in/byeong-hyeon-so-6849611a2/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
