title: Byeong Hyeon So
logo: /assets/img/KakaoTalk_20210718_213903216.jpg
description: 
Aspiring Data Scientist & Social Science Researcher.
<br><br>
<a href="https://www.linkedin.com/in/byeong-hyeon-so-6849611a2/">View My LinkedIn Profile</a>
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
